module.exports = [{
  comm_id: 1,
  description: '立即啟動應急計畫，加強山區的監測和防護措施，以降低可能的災害風險。',
  image: null,
  polling: 3,
  desc_p: '因市長積極應對颱風並加強防護，民眾對市長的應對能力和關懷度有正面印象。',
  funding: -3,
  desc_f: '因為啟動應急計畫和加強監測防護需要額外的財政支出，對市府資金造成負擔。',
  environment: 2,
  desc_e: '因為積極的應對措施有助於減少可能的災害風險，對環境保護產生積極影響。'
}, {
  comm_id: 1,
  description: '我覺得山區崩塌的機率不大，但這可不是在扯淡。我們會像網美修圖一樣，仔細檢查一遍，如果有什麼漏洞，立馬修修補補。',
  image: null,
  polling: -2,
  desc_p: '因市長的態度和修圖比喻被認為不夠謹慎，降低了民眾對市長的信任度。',
  funding: -1,
  desc_f: '因為這個選項下市府省下一些支出，僅使用了少量資金。',
  environment: -3,
  desc_e: '因為市長的樂觀態度可能導致忽視了應對風險的必要性，對環境保護造成負面影響。'
}, {
  comm_id: 1,
  description: '我們會立即協調志願者和社區資源，動員大家一起來強化山區的防護措施，讓我們一起守護家園。',
  image: null,
  polling: -1,
  desc_p: '因市長未表現出主動出資的態度，而是期望民眾自發參與，引起民眾反感。',
  funding: 0,
  desc_f: '因為這個選項強調動員社區資源和志願者，不需大量額外財政支出，對資金有正面影響。',
  environment: 2,
  desc_e: '因為這個選項促進了社區參與，有助於共同應對災害風險，對環境保護產生積極影響。'
}, {
  comm_id: 2,
  description: '我們會持續密切關注颱風發展，確保市區居民的安全。目前看來情況還在掌握中，我們會等到更確定的時候再做出是否放颱風假的決定。',
  image: null,
  polling: 3,
  desc_p: '顯示市長謹慎處理颱風議題，提升市長形象。',
  funding: 0,
  desc_f: '因為未做出具體行動，不對資金有直接影響。',
  environment: 1,
  desc_e: '因為表現出謹慎態度，有助於環境保護。'
}, {
  comm_id: 2,
  description: '我們會立即展開應急計畫，以確保市區居民的安全。就算颱風強度下降，我們也不敢掉以輕心，宣布颱風假是為了確保大家的生命安全。',
  image: null,
  polling: 4,
  desc_p: '顯示市長積極應對，提升市長形象。',
  funding: -1,
  desc_f: '因為提前宣布颱風假可能增加一些額外支出。',
  environment: 2,
  desc_e: '因為積極應對有助於環境保護。'
}, {
  comm_id: 3,
  description: '我們會加強疏散措施和風險預警系統，保障市民的安全。市政府會全力協助居民妥善應對颱風影響，保障大家的安全。',
  image: null,
  polling: 4,
  desc_p: '市長積極應對，提高市民對市長的信心。',
  funding: -3,
  desc_f: '因為需要進行加強措施和疏散計畫，可能增加相應的開支。',
  environment: 2,
  desc_e: '因為市區的風險預警和疏散措施有助於減少可能的災害風險。'
}, {
  comm_id: 3,
  description: '我們鼓勵市民保持冷靜，避免不必要的恐慌。目前沒有立即放颱風假的打算，請市民保持警覺，遵從相關指引。',
  image: null,
  polling: -3,
  desc_p: '市長的發言被認為過於不重視颱風風險。',
  funding: 0,
  desc_f: '因為沒有採取任何措施，故沒有花費資金。',
  environment: -2,
  desc_e: '忽視了颱風可能帶來的潛在風險。'
}, {
  comm_id: 3,
  description: '我們在市區的建築結構相對較為堅固，相信不會有太大的危險。如有變化，我們會隨時作出適當調整。',
  image: null,
  polling: -2,
  desc_p: '市民對市長的信任降低。',
  funding: 0,
  desc_f: '省下了支出。',
  environment: -1,
  desc_e: '因為可能忽視了一些潛在的災害風險。'
}, {
  comm_id: 3,
  description: '集結志願者和社區夥伴，一起來打造最堅固的山區防護牆！我們不只是市政府，我們是不怕颱風的大家庭，動起來！',
  image: null,
  polling: 3,
  desc_p: '市長積極樂觀，市民感受到團結的力量。',
  funding: 0,
  desc_f: '這可是動員社區資源，不需花一大筆錢，財政上也能過得去。',
  environment: 2,
  desc_e: '強調社區參與有助於共同應對災害風險。'
}, {
  comm_id: 4,
  description: '我們將評估現有空地，積極布置臨時停車場，以滿足市民在颱風期間的需求。',
  image: null,
  polling: 2,
  desc_p: '民眾滿意市長願意擴建停車場。',
  funding: 3,
  desc_f: '開放臨時停車場需要額外資金，對市府資金產生一定的負擔。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 4,
  description: '哈哈，停車問題真是個大難題，尤其是颱風天！我們會好好研究怎麼能改進現有的停車場',
  image: null,
  polling: -2,
  desc_p: '民眾不滿市長沒有布置臨時停車場。',
  funding: -1,
  desc_f: '不另設開放臨時停車場，僅使用少量資金在改善現有的停車場。',
  environment: 1,
  desc_e: '提升了現有停車場的利用率。'
}, {
  comm_id: 4,
  description: '非常感謝您的建議，我們會仔細研究開放臨時停車場的可行性，以解決上班族的停車問題。',
  image: null,
  polling: 2,
  desc_p: '正面回應市民建議，顯示市府對居民需求的重視，提升市民滿意度。',
  funding: -2,
  desc_f: '進行可行性研究可能增加一些成本，但相對於直接開放臨時停車場，資金負擔較輕。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 5,
  description: '放假這種事情當然是讓大家開心最重要！這次就讓大家放鬆一下吧！不過，也理解你的處境，不要太苦命啦！！',
  image: null,
  polling: 2,
  desc_p: '市長表現幽默且願意聆聽市民聲音，提升民調評價。',
  funding: 0,
  desc_f: '',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 5,
  description: '上班族的辛苦我們一點都不會忽視。我會鼓勵企業主從優考慮薪資調整或提供其他福利。',
  image: null,
  polling: 4,
  desc_p: '市長表現積極關心上班族權益，提高民調評價。',
  funding: -1,
  desc_f: '由於鼓勵雇主提供薪資優惠，可能對市府資金有些微影響。',
  environment: 2,
  desc_e: '市長的提議有助於改善工作環境，對整體社會氛圍產生正面影響。'
}, {
  comm_id: 5,
  description: '上班確實不能輕易放假。我們會繼續密切關注颱風情況，同時提供必要的應對措施，確保郊區居民的安全。',
  image: null,
  polling: 1,
  desc_p: '因市長表現出理解和考慮上班族的立場，提高市民對市長的理解和支持。',
  funding: -1,
  desc_f: '因為需要提供相應的應對措施，可能會增加一些額外的支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 6,
  description: '我會嚴密關注交通狀況，若有需要，會提前宣布颱風假，確保市民的安全。',
  image: null,
  polling: 3,
  desc_p: '，因為市長表現出關心市民安全的態度。',
  funding: -2,
  desc_f: '因為提前放颱風假會影響市政運作，增加成本。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 6,
  description: '考慮到上班族的需求，我們會加強公共交通運輸系統。',
  image: null,
  polling: 2,
  desc_p: '因為市長提出了提升公共交通的解決方案。',
  funding: -3,
  desc_f: '因為改善公共交通可能需要額外資金投入。',
  environment: 2,
  desc_e: '因為增加公共交通使用可能有助於減少單獨開車的情況。'
}, {
  comm_id: 6,
  description: '我明白上班族的困境，但必須謹慎考慮，或許我們可以提供其他安全方案。',
  image: null,
  polling: 1,
  desc_p: '市長表現出謹慎思考，但未能完全滿足市民需求。',
  funding: -1,
  desc_f: '提供其他安全方案可能需要額外資金支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 7,
  description: '我們將維持正常上班，但會加強防颱工程，確保市區安全。',
  image: null,
  polling: 1,
  desc_p: '民眾滿意市府有提供一定的保護措施。',
  funding: -1,
  desc_f: '相對較低的經濟負擔，但仍需投入預防工程。',
  environment: 1,
  desc_e: '強調加強防颱工程有助於環境保護。'
}, {
  comm_id: 7,
  description: '保護市民最重要，我將宣布颱風假，確保大家安全，雙倍薪資是應得的。',
  image: null,
  polling: 5,
  desc_p: '市民滿意市長關心安全。',
  funding: -2,
  desc_f: '支付雙倍薪資造成一定負擔。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 7,
  description: '颱風來臨，但生活得繼續，我們不宣布颱風假，大家配合應對。',
  image: null,
  polling: -4,
  desc_p: '市民感受市長不關心安全。',
  funding: 2,
  desc_f: '節省雙倍薪資支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 8,
  description: '我會強調災害防範的重要性，並提供支援措施，同時盡量減少對正常工作的干擾。',
  image: null,
  polling: 2,
  desc_p: '強調災害防範有助於獲得市民支持。',
  funding: -1,
  desc_f: '提供支援措施可能增加支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 8,
  description: '我理解上班族的關切，我會仔細評估颱風的嚴重程度，確保市民的生命安全優先。',
  image: null,
  polling: 3,
  desc_p: '市民感受到市長重視安全，提升滿意度。',
  funding: -2,
  desc_f: '需投入額外資金應對颱風影響。',
  environment: 1,
  desc_e: '採取謹慎態度有助於環境保護。'
}, {
  comm_id: 8,
  description: '理解上班族的需求，我會謹慎評估颱風假對工作的衝擊，保障市區運作順暢，同時提供適度的休息時間。',
  image: null,
  polling: 2,
  desc_p: '因市長表現理解和謹慎，受到上班族支持。',
  funding: 0,
  desc_f: '',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 9,
  description: '我會儘量平衡上班族的需求，但在安全優先的原則下，我傾向給予颱風假。',
  image: null,
  polling: 2,
  desc_p: '因為考慮到安全，大多數人可能支持這個回答。',
  funding: -1,
  desc_f: '因為颱風假可能導致部分企業損失，影響市區的經濟。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 9,
  description: '我會積極協助需要處理緊急事務的上班族，但同時提供額外的防災措施，讓大家感到安心。',
  image: null,
  polling: 4,
  desc_p: '因為此回答考慮到各方需求，獲得多數人支持。',
  funding: -2,
  desc_f: '因為增加防災措施可能需要額外經費，對資金造成一定影響。',
  environment: 1,
  desc_e: '因為提升防災措施可能帶來些微環境改善。'
}, {
  comm_id: 9,
  description: '我將強烈支持颱風假，確保市民安全，但也會提供相應的資源協助上班族應對緊急狀況。',
  image: null,
  polling: 3,
  desc_p: '因為市長表現出關懷，得到市民部分支持。',
  funding: -3,
  desc_f: '因為支持颱風假和提供額外資源可能對資金造成較大影響。',
  environment: 2,
  desc_e: '因為颱風假有助於減少交通與能源消耗，對環境有正面影響。'
}, {
  comm_id: 10,
  description: '我了解上班族在颱風假的狀況，我將盡力爭取提供相應的協助，包括與企業協商，減少加班要求，同時推動相應的經濟救助計畫，以減輕經濟負擔。',
  image: null,
  polling: 3,
  desc_p: '因為市長表現出關心和積極解決問題的態度。',
  funding: -2,
  desc_f: '因為實施經濟救助計畫需要耗費一定的資金。',
  environment: 1,
  desc_e: '因為透過協商減少加班可能有助於緩解環境壓力。'
}, {
  comm_id: 10,
  description: '我將提出相應的法規，禁止企業在颱風假期間要求加班，以保障上班族的權益。同時，我將督促企業提供適當的補償措施，以彌補因颱風假帶來的損失。',
  image: null,
  polling: 4,
  desc_p: '因為市長採取了積極的立法行動，維護了上班族的權益。',
  funding: -3,
  desc_f: '因為推動法規和督促企業提供補償可能需要一定的資金支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 10,
  description: '颱風假是不可避免的狀況，我建議上班族提前做好應對準備，包括適時告知雇主、合理分配工作進度，以減少颱風假對工作的衝擊。',
  image: null,
  polling: 1,
  desc_p: '因為市長提供了一些建議，但未採取積極的行動。',
  funding: 0,
  desc_f: '因為市長未提出具體的經濟支援計畫。',
  environment: -3,
  desc_e: '因為未採取具體行動可能使環境壓力增加，上班族感受到市府的無力。'
}, {
  comm_id: 11,
  description: '非常感謝外送人員的辛勞，我們會加強颱風期間的交通管制，確保道路安全，但停班停課可能會對市民的生活造成不便，我們會盡量維持正常運作。',
  image: null,
  polling: 3,
  desc_p: '因為市長表現出尊重外送人員的立場，同時考慮市民的生活需求，顯得理性和溝通能力。',
  funding: -1,
  desc_f: '因為需要加強交通管制可能會增加一些成本。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 11,
  description: '在颱風來臨前，我們會提前宣布停班停課，以確保市民的安全。外送人員的安全是我們首要考慮的事項。',
  image: null,
  polling: 1,
  desc_p: '因為市長表現出對市民安全的關切，獲得正面評價。',
  funding: -2,
  desc_f: '因為停班停課可能會對經濟造成損失，但這也可以視為為了市民安全的必要支出。',
  environment: 1,
  desc_e: '停班停課有助於減少交通和能源消耗，對環境有一定的積極影響。'
}, {
  comm_id: 11,
  description: '我理解外送人員的困境，但停班停課會對經濟造成不良影響，我們可以呼籲市民在颱風來臨前儘量準備，外送公司也應提供額外的保障給予外送人員。',
  image: null,
  polling: 1,
  desc_p: '市長表現出對經濟的關切，提供了一種折衷的解決方案。',
  funding: -2,
  desc_f: '因為外送公司提供額外的保障可能需要額外支出。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 12,
  description: '我們會考慮在雨天實施臨時的外送禁令，以減少外送活動對城市交通和環境的影響。同時，我們會研究是否能提供其他形式的補償，以保障外送人員的權益。',
  image: null,
  polling: -2,
  desc_p: '市民可能會對外送禁令感到不滿，影響市政滿意度。',
  funding: -1,
  desc_f: '外送禁令可能影響城市的經濟收入，但在其他方面的補償可能會有一定成本。',
  environment: 4,
  desc_e: '透過禁令可以減少外送活動對環境的不利影響，提高城市的環境品質。'
}, {
  comm_id: 12,
  description: '我們會推出一些政策，鼓勵市民在雨天減少外送需求，例如提供泡麵促銷優惠鼓勵市民提前備糧在家。',
  image: null,
  polling: 1,
  desc_p: '市民會感到市長考慮到外送人員的安全，但可能對促銷優惠政策持有不同意見。',
  funding: -3,
  desc_f: '因為可能需要推出促銷優惠，對城市預算造成一定的負擔。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 12,
  description: '我們會積極保障外送人員的工作權，確保他們在雨天有足夠的工作機會。',
  image: null,
  polling: -2,
  desc_p: '因為市民認為市長不關心安全問題。',
  funding: 0,
  desc_f: '',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 13,
  description: '在面對颱風威脅時，我們會採取一個平衡的立場。我們將加強宣導民眾保持安全，同時避免全面禁止外出，以保障個人自由。這樣的政策可以在颱風來臨時減緩經濟停滯，同時不至於嚴重損害市民的基本權利。',
  image: null,
  polling: 2,
  desc_p: '因為這樣的回應顯示市長在自由和安全之間找到了平衡，可能獲得部分市民的支持。',
  funding: -1,
  desc_f: '因為雖然政策相對保守，但也需要一些資金用於宣導和應急措施。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 13,
  description: '在颱風威脅下，我們將採取強硬措施，全面禁止民眾外出。這是為了確保每個市民的生命安全，我們不惜一切代價保護市民。雖然這可能限制自由，但我們認為在這個時刻，安全是最重要的。',
  image: null,
  polling: -4,
  desc_p: '因為強硬的措施可能引起部分市民反感，認為政府過度干預。',
  funding: -3,
  desc_f: '因為實施全面禁令需要大量資金，包括應急措施和執行力度。',
  environment: 1,
  desc_e: '因為全面禁令可能減少人造活動，對環境有一定的正面影響。'
}, {
  comm_id: 13,
  description: '我們將依循科學建議，實施有針對性的外出限制。這包括封閉易受颱風威脅的區域，但同時保留對其他地區的正常生活。這樣可以最大程度地保護市民，同時減少對經濟的不利影響。',
  image: null,
  polling: 3,
  desc_p: '因為此回應顯示市長重視科學建議，同時也考慮到經濟因素，可能受到廣泛支持。',
  funding: -2,
  desc_f: '因為雖然政策相對於全面禁令較節制，但仍需資金應對區域性的應急情況。',
  environment: 0,
  desc_e: ''
}, {
  comm_id: 14,
  description: '「當然，我們將全力與媒體合作，確保颱風相關信息的即時傳達。市民的安全是我們首要關注的事項。」',
  image: null,
  polling: 3,
  desc_p: '正面回應有助於提升市民對市長的信任。',
  funding: -2,
  desc_f: '提供即時信息可能需要額外的資金投入。',
  environment: 2,
  desc_e: '積極應對颱風可以減少環境損害，例如提前疏散減少災害。'
}, {
  comm_id: 14,
  description: '「我們已經有相應的應急計劃，並會確保颱風相關信息在適當的時間內提供給媒體。」',
  image: null,
  polling: 1,
  desc_p: '穩健回應，但缺乏即時性可能稍微減分。',
  funding: -1,
  desc_f: '維持計劃有少量資金支出。',
  environment: 1,
  desc_e: '有應急計劃有助於環境保護。'
}, {
  comm_id: 14,
  description: '「新聞媒體應該自行負責提供準確的颱風信息，市政府有更重要的事務需要處理。」',
  image: null,
  polling: -5,
  desc_p: '對市民需求漠不關心，可能引起不滿。',
  funding: 0,
  desc_f: '節省資金，但可能引起公憤。',
  environment: -3,
  desc_e: '無法提前應對颱風可能導致更嚴重的環境損害'
}, {
  comm_id: 15,
  description: '「我們會提前通知民眾有颱風來臨的可能性，但不會馬上公布放假，以避免引起不必要的慌亂。」',
  image: null,
  polling: 2,
  desc_p: '對民眾的提前通知有正面影響。',
  funding: 0,
  desc_f: '不涉及資金問題。',
  environment: 1,
  desc_e: '提前通知可能減少外出，對環境有輕微正面影響。'
}, {
  comm_id: 15,
  description: '「我們將在颱風確定來襲後迅速公布應對方案，包括是否放假。我們相信居民有自主判斷的能力。」',
  image: null,
  polling: -2,
  desc_p: '雖有即時反應的承諾，但對於是否放假並不在意，民眾不滿。',
  funding: 0,
  desc_f: '不涉及資金問題。',
  environment: 0,
  desc_e: '提前通知和即時反應之間的平衡。'
}, {
  comm_id: 15,
  description: '「我們會等到颱風確定來襲後再公布消息，以避免不必要的困擾。我們相信市民擁有足夠的應變能力。」',
  image: null,
  polling: -2,
  desc_p: '市民感到市府不夠關心和主動。',
  funding: 0,
  desc_f: '不涉及資金問題。',
  environment: -1,
  desc_e: '因為沒有提前公布消息，可能導致市民在颱風來臨前外出，對環境有輕微負面影響。'
}, {
  comm_id: 16,
  description: '「我們已經在颱風來臨前就充分備妥了免費沙包，以應對可能的水患。我們將積極分發給低窪地區的市民，確保他們的安全。」',
  image: null,
  polling: 3,
  desc_p: '因為市民感受到政府的積極應對，提高對市府的信心。',
  funding: -2,
  desc_f: '因為提供免費沙包需要相應的經費支出。',
  environment: 1,
  desc_e: '因為這有助於減輕水患，對環境有積極影響。'
}, {
  comm_id: 16,
  description: '「免費沙包並非我們主要的應對方案，我們將集中資源在強化排水系統和提升市民的颱風應變能力上。這樣才能真正解決問題，不只是治標而已。」',
  image: null,
  polling: -1,
  desc_p: '因為市民可能感受到市府對颱風主要問題的應對不夠積極。',
  funding: 0,
  desc_f: '因為主要資源集中在長遠應對方案上，可能節省一些短期支出。',
  environment: -2,
  desc_e: '因為缺少即時應對措施，可能導致環境受損。'
}, {
  comm_id: 16,
  description: '「我們已經開始免費沙包的發放，並且正在協調志願者協助市民搭建防水設施。這是我們的首要任務，確保市民在颱風中的安全。」',
  image: null,
  polling: 4,
  desc_p: '因為市府積極應對並協調志願者，提高市府形象。',
  funding: -3,
  desc_f: '因為提供免費沙包和協助搭建設施都需要相應的經費支出。',
  environment: 2,
  desc_e: '因為積極應對有助於減輕災害可能帶來的環境影響。'
}, {
  comm_id: 17,
  description: '「我們已經有相應的颱風應變計畫，包括強風期間的路樹固定措施。市區的基礎建設相當穩固，我們相信可以有效應對颱風帶來的風險。」',
  image: null,
  polling: 2,
  desc_p: '顯示市政府有應對措施，提高市區居民的信心。',
  funding: 0,
  desc_f: '無額外支出或收入。',
  environment: 1,
  desc_e: '采取固定措施有助於減少樹木傾倒對環境的損害。'
}, {
  comm_id: 17,
  description: '「我們將全面檢討現有的路樹固定計劃，確保其有效性。同時，我們會加強宣傳，呼籲市民在颱風前採取必要的安全措施。」',
  image: null,
  polling: 1,
  desc_p: '市民感受到市府積極檢討並提升防災計劃，增加滿意度。',
  funding: -1,
  desc_f: '由於檢討現有計劃可能需要一些額外資金，導致資金減少。',
  environment: 1,
  desc_e: '加強宣傳呼籲市民在颱風前採取安全措施，有助於減少風災對環境的影響，提高環保意識。'
}, {
  comm_id: 17,
  description: '「我們已經有一個完善的路樹固定計劃，不需要再進一步加強。我相信現有的措施足以應對颱風帶來的風險。」',
  image: null,
  polling: -3,
  desc_p: '市民可能感到市府對颱風風險的輕忽，對應急措施的不滿。',
  funding: 0,
  desc_f: '因為在此情況下無需額外經費，資金狀況保持中立。',
  environment: -2,
  desc_e: '市府對路樹固定計劃的滿足感可能導致對環境風險的忽視，市民擔憂環境可能受到颱風的威脅。'
}, {
  comm_id: 18,
  description: '「我們不能一直拖延基礎建設，這樣會影響城市的發展。我們會加強應急服務，同時繼續推進必要的建設工程。」',
  image: null,
  polling: -2,
  desc_p: '民眾擔心災害風險。',
  funding: -2,
  desc_f: '沒有接受建議，繼續進行建設。',
  environment: -4,
  desc_e: '有一部分環境保護份子對此不滿。'
}, {
  comm_id: 18,
  description: '「考慮到颱風風險，我們會優先應對災害，暫緩不急迫的基礎建設。」',
  image: null,
  polling: 3,
  desc_p: '表現出對民眾安全的關心。',
  funding: -1,
  desc_f: '因暫緩建設而省下的資金。',
  environment: 1,
  desc_e: '因為優先應對災害可能的風險。'
}, {
  comm_id: 18,
  description: '「我們會立即停止一切工程，將資金用於加強應急服務和颱風防禦。」',
  image: null,
  polling: 4,
  desc_p: '市民對於強化應急服務和防禦措施的正面評價。',
  funding: 0,
  desc_f: '將資金改用於應急服務及防禦，並沒有減少支出。',
  environment: 2,
  desc_e: '可能提前進行環境措施。'
}, {
  comm_id: 19,
  description: '「理解大家的心情，但我們必須優先考慮市區的安全。暫時不考慮放颱風假，我們會盡力確保市區居民的安全。」',
  image: null,
  polling: -2,
  desc_p: '因為沒有滿足市民的期望。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 19,
  description: '「我們會評估颱風的危險程度，若確定有需要，我們會考慮放颱風假。不過，首要目標是確保市區居民的安全。」',
  image: null,
  polling: 1,
  desc_p: '因為顯露了對市民需求的關心。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 19,
  description: '「我理解學生想要休息的心情，但我們也要考慮到颱風可能帶來的危險和損害。安全第一，我們會密切關注颱風動向，必要時會宣布假期。」',
  image: null,
  polling: 2,
  desc_p: '考慮學生心情。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 20,
  description: '「年輕人的冒險精神是值得鼓勵的，但在面對颱風這樣的天災時，我們必須以安全為先。我們將提前做好應對措施，保障市民的安全。同時，我們也會安排一些室內活動，讓大家在安全的環境中度過這段時間。」',
  image: null,
  polling: 2,
  desc_p: '市民感受到市政的積極應對，提升支持度。',
  funding: -1,
  desc_f: '需要花費資金提前做好應對措施。',
  environment: 1,
  desc_e: '積極應對有助於減少環境損害。'
}, {
  comm_id: 20,
  description: '「颱風不是開玩笑的事情。為了市民的安全，我們將全面應對，提前做好防護工作，並宣布放假以確保大家的安全。我們也會提供一些在家中參與的有趣活動，讓大家在安全的環境中享受假期。」',
  image: null,
  polling: 3,
  desc_p: '市民感受到市政的積極應對，提升支持度。',
  funding: -3,
  desc_f: '需要花費資金提前做好應對措施，並宣布放假。',
  environment: 2,
  desc_e: '積極應對有助於減少環境損害。'
}, {
  comm_id: 20,
  description: '「我們鼓勵市民保持冒險精神，但也需要謹慎應對自然災害。我們將提供相應的防災措施，同時讓市民感受刺激的一天。」',
  image: null,
  polling: 1,
  desc_p: '對冒險精神表示理解，但不完全同意。',
  funding: -1,
  desc_f: '增加防災措施的成本。',
  environment: -1,
  desc_e: '可能影響生活品質。'
}, {
  comm_id: 21,
  description: '「我理解補課對學生來說可能不是最好的解決方式，但我們必須確保民眾的安全。我會與學校合作，努力減少補課的負擔。」',
  image: null,
  polling: 2,
  desc_p: '有理解市民，並願意採取合作的行動。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 21,
  description: '「我明白補課對學生不太公平，但是我們不能輕忽天氣的不穩定性。我會嚴謹評估颱風的情況，只有在必要的時候才會停課。」',
  image: null,
  polling: -1,
  desc_p: '理解但較保守。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 21,
  description: '「我理解學生不喜歡補課，但颱風的風險不可忽視。我會盡量在事前提前通知，以便安排補課。」',
  image: null,
  polling: 1,
  desc_p: '表現出對學生感受的理解，並承諾提前通知。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 22,
  description: '理解學生的擔憂，但考試的時間表是經過慎重考慮的，不能因個別需求而改變。我們會提供額外的補充教材和支援，希望學生能克服這個挑戰。',
  image: null,
  polling: 1,
  desc_p: '有理解學生，並提供其他支援。',
  funding: -1,
  desc_f: '提供額外的補充教材和支援。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 22,
  description: '我們尊重學生的聲音，將向學校提出建議，但不能保證一定能延期考試。我們建議學生積極備戰，同時我們會提供支援，請大家理解。',
  image: null,
  polling: 2,
  desc_p: '尊重學生聲音，積極尋求解決方案',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 22,
  description: '理解學生的壓力，我們將向教育部提出延期考試的請求，同時向學區爭取資金用於提供額外的教育資源。',
  image: null,
  polling: 1,
  desc_p: '提供更長的備考時間，取得民眾認同。',
  funding: 2,
  desc_f: '獲得額外的教育資源支援。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 23,
  description: '提前宣布颱風假確實是一種保護措施，但我們需要更多的討論和評估。我會與相關方面進行協商，確保最佳的方案被制定出來。',
  image: null,
  polling: 1,
  desc_p: '民眾感覺市長在綜合考慮各方面意見。',
  funding: 0,
  desc_f: '不影響。',
  environment: 1,
  desc_e: '表示願意考慮災害應對的方案。'
}, {
  comm_id: 23,
  description: '我完全支持企業的提案，我們民眾也應該有足夠的時間做好應對準備。我會積極宣導提前宣布颱風假的必要性。',
  image: null,
  polling: 4,
  desc_p: '民眾感覺市長對他們的安全關切。',
  funding: 0,
  desc_f: '不影響。',
  environment: 2,
  desc_e: '提前宣布颱風假有助於減少可能的災害。'
}, {
  comm_id: 23,
  description: '我完全理解企業的立場，提前宣布颱風假確實有助於員工做好準備，保障他們的安全。這種合作精神也有助於我們市區的災害應對，希望未來能有更多的協作機會。',
  image: null,
  polling: 3,
  desc_p: '民眾認為政府顧及企業和民眾的安全。',
  funding: 2,
  desc_f: '企業在協作過程中提供了一些金錢支援。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 24,
  description: '我會儘量平衡企業和市民的需求，我們可以提供相應的支援和協助，但未來的決策必須基於公共安全和市民福祉。',
  image: null,
  polling: 1,
  desc_p: '民眾感受到市長考慮各方。',
  funding: -1,
  desc_f: '提供支援。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 24,
  description: '現在還難以確定颱風的影響，我們將密切觀察情勢。如果有需要，我會立即發布相應的通告，確保市區的運作不受太大干擾。',
  image: null,
  polling: -1,
  desc_p: '市民可能感受到不夠主動。',
  funding: 0,
  desc_f: '不影響。',
  environment: -1,
  desc_e: '缺乏預防措施。'
}, {
  comm_id: 24,
  description: '「我會與企業進行密切合作，共同制定應對颱風的應急計劃。我們會平衡市區經濟運作和市民安全之間的需求，以確保最佳的結果。」',
  image: null,
  polling: 2,
  desc_p: '市長表現出對企業的合作態度。',
  funding: 0,
  desc_f: '取得平衡，沒有明顯的正負影響。',
  environment: 2,
  desc_e: '應急計劃的制定有助於減少颱風對環境的影響。'
}, {
  comm_id: 25,
  description: '「我了解企業的困境，但為了市民的安全，我們必須宣布颱風假，以減少災害風險。我會積極尋找支援方案，以減輕企業的營運負擔。」',
  image: null,
  polling: 2,
  desc_p: '市民認為市長有為市民安全考慮。',
  funding: -3,
  desc_f: '因為需要支援企業，政府支出增加。',
  environment: 1,
  desc_e: '宣布颱風假有助於減少災害風險。'
}, {
  comm_id: 25,
  description: '「企業的聲音很重要，我會謹慎考慮並在宣布颱風假後立即展開救災工作，以減少對企業的衝擊。」',
  image: null,
  polling: 3,
  desc_p: '市民認為市長考慮全面。',
  funding: -1,
  desc_f: '用於救災工作。',
  environment: 1,
  desc_e: '宣布颱風假有助於減少災害風險。'
}, {
  comm_id: 25,
  description: '「我理解企業的立場，但颱風假是為了全體市民的利益。我會協助企業爭取補助，以減少他們的損失，請企業體諒。」',
  image: null,
  polling: 1,
  desc_p: '市民認為市長顧及企業利益。',
  funding: -2,
  desc_f: '政府提供一部分補助，支出增加。',
  environment: 1,
  desc_e: '宣布颱風假有助於減少災害風險。'
}, {
  comm_id: 26,
  description: '理解大家的辛苦，我也將爭取更多的補助，以支援企業支付更多的加班費，保障市民權益。',
  image: null,
  polling: 3,
  desc_p: '表現出積極爭取市民權益。',
  funding: -2,
  desc_f: '將資金用於發放補助。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 26,
  description: '確實有加班費，但我將提倡企業自發性地提供更多福利，以提升市區居民的整體生活品質。',
  image: null,
  polling: 2,
  desc_p: '強調提升生活品質，符合市民期望。',
  funding: 0,
  desc_f: '提倡企業自發，不會有資金支出。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 26,
  description: '颱風假當然是不得已的情況，但我們必須保持市區的運轉。我會提倡彈性工時，讓大家能更靈活地應對災害，同時也會增加資金投入，改善市區的基礎建設。',
  image: null,
  polling: 2,
  desc_p: '提倡彈性工時受到好評。',
  funding: -3,
  desc_f: '增加基礎建設投入。',
  environment: 1,
  desc_e: '改善基礎建設。'
}, {
  comm_id: 26,
  description: '提醒民眾儲備食物和水，減少外出，減少服務業的工作負擔。',
  image: null,
  polling: 2,
  desc_p: '市民對於提醒儲備感到滿意。',
  funding: 0,
  desc_f: '不影響。',
  environment: 0,
  desc_e: '不影響。'
}, {
  comm_id: 27,
  description: '我們將仔細評估情況，確保政策公平，有助於社會穩定。',
  image: null,
  polling: -3,
  desc_p: '表現出缺乏對民眾需求的理解。',
  funding: 0,
  desc_f: '無直接影響。',
  environment: 0,
  desc_e: '無直接關聯。'
}, {
  comm_id: 27,
  description: '放假是一回事，保證大家能順利度過颱風是另一回事，我們會全力保護市民的安全。',
  image: null,
  polling: 2,
  desc_p: '展現出對市民安全的關注。',
  funding: -1,
  desc_f: '可能需要增加資源用於安全措施。',
  environment: 0,
  desc_e: '無直接影響。'
}, {
  comm_id: 27,
  description: '不准放假？那好，我們就取消所有假期，全年無休！',
  image: null,
  polling: -5,
  desc_p: '嚴厲的態度會引起公眾不滿。',
  funding: -3,
  desc_f: '可能引發勞工抗議或訴訟，增加了支出。',
  environment: 0,
  desc_e: '與環境無直接關聯。'
}, {
  comm_id: 28,
  description: '我們將考慮這個建議，並在保障市民安全的前提下作出最合適的決定。',
  image: null,
  polling: 2,
  desc_p: '表現了對市民安全的關注。',
  funding: 1,
  desc_f: '增加了額外收入。',
  environment: 0,
  desc_e: '與環境無直接關聯。'
}, {
  comm_id: 28,
  description: '這確實是一個有趣的想法，但我們不能以犧牲公眾安全為代價來迎合商業利益。',
  image: null,
  polling: 3,
  desc_p: '幽默回應增加了民眾對市長的好感。',
  funding: 0,
  desc_f: '無直接影響。',
  environment: 0,
  desc_e: '與環境無直接關聯。'
}, {
  comm_id: 28,
  description: '當然！讓我們忽略安全問題，盡情迎接額外收入吧！',
  image: null,
  polling: -4,
  desc_p: '示了對市民安全的漠視。',
  funding: 3,
  desc_f: '增加了額外收入。',
  environment: -2,
  desc_e: '忽略了可能對環境造成的影響。'
}, {
  comm_id: 29,
  description: '我們將密切關注服務業的工作負擔，並努力提供支援和協助。',
  image: null,
  polling: 2,
  desc_p: '表現了市長對市民關注的態度。',
  funding: -1,
  desc_f: '可能需要增加支援服務的開支。',
  environment: 0,
  desc_e: '與環境無直接關聯。'
}, {
  comm_id: 29,
  description: '放颱風假只會增加您們的收入，對您們是好事！',
  image: null,
  polling: -4,
  desc_p: '市長的無知可能引起市民的不滿。',
  funding: 0,
  desc_f: '無直接影響。',
  environment: 0,
  desc_e: '無直接影響。'
}, {
  comm_id: 29,
  description: '也許我們可以舉辦一場線上的颱風派對，讓市民在颱風期間能夠在不外出的情況下，有一個輕鬆愉快的活動！',
  image: null,
  polling: 4,
  desc_p: '市長的幽默和創意可能贏得市民的好感。',
  funding: -3,
  desc_f: '舉辦活動可能需要大量的資金支出。',
  environment: 0,
  desc_e: '與環境無直接關聯。'
}]
